[build-system]
requires = ["hatchling<=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "gloryxr"
version = "0.1.0"
description = "The next generation of the GLORYx metabolite prediction system"
readme = "README.rst"
requires-python = ">=3.13"
license = "GPL-3.0"
authors = [
    { name = "Leo Gaskin", email = "leo.gaskin@univie.ac.at" },
    { name = "Roxane Jacob", email = "roxane.axel.jacob@univie.ac.at" },
]

dependencies = [
    "cdpkit>=1.2.3",
    "fame3r>=2.0.0",
    "rdkit>=2025.3.3",
]

[project.optional-dependencies]
awesom = ["awesom"]

[dependency-groups]
build = ["build"]
tests = [
    "pytest>=8.4.1",
    "syrupy>=4.9.1",
]
docs = [
    "myst-nb>=1.4.0",
    "sphinx>=8.2.3",
    "sphinx-book-theme>=1.1.4",
    "sphinx-copybutton>=0.5.2",
]
dev = [
    "fame3r[cli]",
    "jupyter>=1.1.1",
    "jupyter-ruff>=0.3.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.5",
    "ruff>=0.11.13",
    "ty>=0.0.62",
    "zuban>=0.7.2",
    { include-group = "build" },
    { include-group = "tests" },
    { include-group = "docs" },
]

[tool.hatch.build.targets.sdist]
only-include = ["src/gloryxr"]

[tool.hatch.build.targets.wheel]
packages = ["src/gloryxr"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.pyright]
typeCheckingMode = "basic"
exclude = [".venv", "**/*.ipynb"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.uv.sources]
awesom = { git = "https://github.com/molinfo-vienna/aweSOM" }
