from os import PathLike
from pathlib import Path
from typing import Any, Self, override

import joblib
import numpy as np
from fame3r.descriptors import FAME3RVectorizer
from rdkit.Chem.rdChemReactions import ChemicalReaction

from gloryxr.models import ModelProvider
from gloryxr.utils import extract_smiles_for_soms

__all__ = ["MultiFAME3RModelProvider"]


class MultiFAME3RModelProvider(ModelProvider):
    """A model provider for a family of reaction-class specific FAME3R models.

    When used with our provided FAME3R models, predictions generated
    using this class will closely follow those generated by the
    original GLORYx implementation.

    """

    def __init__(self, models: dict[str, Any]) -> None:
        self.models: dict[str, Any] = models
        self.vectorizer = FAME3RVectorizer().fit()

    @classmethod
    def load(cls, model_path: PathLike[str] | str) -> Self:
        """Load a list of reaction-class specific FAME3R models from a local directory.

        The `.joblib` files containing the models should have their
        corresponding reaction type as their file name.

        """

        model_paths = list(Path(model_path).glob("*.joblib"))
        if len(model_paths) == 0:
            raise RuntimeError(f"No models could be found at '{model_path}'")

        models = {}
        for model_path in model_paths:
            models[model_path.stem] = joblib.load(filename=model_path)

        return cls(models)

    @override
    def predict_proba(
        self,
        reactions: list[ChemicalReaction],
    ) -> np.ndarray[tuple[int], np.dtype[np.float64]]:
        results = []

        for rxn in reactions:
            priority = rxn.GetProp("_Priority")
            if priority == "uncommon":
                priority_factor = 0.2
            else:
                priority_factor = 1.0
            subset = rxn.GetProp("_Subset")

            reactive_atoms = extract_smiles_for_soms(rxn.GetReactantTemplate(0))
            if len(reactive_atoms) == 0:
                # TODO: fix this using rules
                results.append(np.nan)
                continue

            descriptors = self.vectorizer.transform(
                np.array(reactive_atoms).reshape(-1, 1)
            )
            predictions = self.models[subset].predict_proba(descriptors)

            results.append(predictions[:, -1].max() * priority_factor)

        return np.asarray(results)
